apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: log-analytics
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 5173
  type: ClusterIP

